// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjyNBsa_USUYJz6e_Pwamwf2Fj3zVXE4',
    appId: '1:722574504072:web:8bb73183f56760e56e6f3d',
    messagingSenderId: '722574504072',
    projectId: 'flutter-74166',
    authDomain: 'flutter-74166.firebaseapp.com',
    storageBucket: 'flutter-74166.appspot.com',
    measurementId: 'G-MV9T65TM2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5ps1RNcJ8Cfx5UQTeiTpNrtUbl4AV00',
    appId: '1:722574504072:android:d27d47fde258cceb6e6f3d',
    messagingSenderId: '722574504072',
    projectId: 'flutter-74166',
    storageBucket: 'flutter-74166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOz15iiIDC1TxZmQ6TRFiEfukt_slDx4',
    appId: '1:722574504072:ios:e46178441480542c6e6f3d',
    messagingSenderId: '722574504072',
    projectId: 'flutter-74166',
    storageBucket: 'flutter-74166.appspot.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOz15iiIDC1TxZmQ6TRFiEfukt_slDx4',
    appId: '1:722574504072:ios:b0643fa4f05a389a6e6f3d',
    messagingSenderId: '722574504072',
    projectId: 'flutter-74166',
    storageBucket: 'flutter-74166.appspot.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
